name: discovertermo
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.13
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - pytorch-lightning
  - torchmetrics
  - pyg
  - pip
  - pip:
#     - .
      - einops
      - hydra-core
      - numpy
      - matplotlib
      - plotly
      - pymatgen
      - omegaconf
      - pandas
      - scikit-learn
      - scipy
      - tables
      - tqdm
      - tabulate
      - chem_wasserstein
      - seaborn
# cd tsl 
# pip install -e .